package com.clilystudio.zuzi;
/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Sheng' at '16-7-20 下午9:28' with Gradle 2.13
 *
 * @author Sheng, @date 16-7-20 下午9:28
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
