package com.clilystudio.zuzi;
import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Sheng' at '16-7-20 下午9:28' with Gradle 2.13
 *
 * @author Sheng, @date 16-7-20 下午9:28
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
